export const tailwindTokens = {
  tailwindbg: {
    "accent-active": "#410c48",
    "accent-default": "#571060",
    "accent-disabled": "#cdb7cf",
    "accent-hover": "#7a3e81",
    "accent-subtle": "#f3eef5",
    "brand-default": "#e11a2c",
    "brand-strong": "#ca1727",
    caution: "#fff3cd",
    critical: "#f8d7da",
    default: "#ffffff",
    info: "#cce5ff",
    positive: "#d4edda",
    stronger: "#333333",
    subtle: "#f6f6f6",
  },
  tailwindtext: {
    "accent-active": "#410c48",
    "accent-default": "#571060",
    "accent-disabled": "#cdb7cf",
    "accent-hover": "#7a3e81",
    caution: "#856404",
    "critical-strong": "#ee0200",
    "critical-stronger": "#721c24",
    default: "#231f20",
    disabled: "#cccccc",
    info: "#004085",
    inverse: "#ffffff",
    "positive-strong": "#008a1f",
    "positive-stronger": "#155724",
    subtle: "#666666",
  },
  tailwindborder: {
    "accent-active": "#410c48",
    "accent-default": "#571060",
    "accent-disabled": "#cdb7cf",
    "accent-hover": "#7a3e81",
    caution: "#ffeeba",
    "critical-strong": "#ee0200",
    "critical-subtle": "#f5c6cb",
    default: "#cccccc",
    disabled: "#cccccc",
    info: "#b8daff",
    inverse: "#ffffff",
    "positive-strong": "#008a1f",
    "positive-subtle": "#c3e6cb",
  },
};

export default tailwindTokens;
